"""empty message

Revision ID: 64404acf4b68
Revises: 5d05b500ec6b
Create Date: 2024-11-14 01:13:16.995289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64404acf4b68'
down_revision = '5d05b500ec6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_bank', schema=None) as batch_op:
        batch_op.alter_column('uploadedDate',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_bank', schema=None) as batch_op:
        batch_op.alter_column('uploadedDate',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
