"""empty message

Revision ID: 6f5f3239795b
Revises: 704fb5ce7936
Create Date: 2024-12-12 18:32:51.631824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5f3239795b'
down_revision = '704fb5ce7936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('picture_url', sa.Text(), nullable=False),
    sa.Column('model_url', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=25), nullable=True))
        batch_op.create_unique_constraint(None, ['userName'])
        batch_op.create_foreign_key(None, 'user', ['userId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('userName')

    op.drop_table('model')
    # ### end Alembic commands ###
