"""Initial migration after cleanup

<<<<<<<< HEAD:migrations/versions/e3945611da63_initial_migration_after_cleanup.py
Revision ID: e3945611da63
Revises: 
Create Date: 2024-12-17 20:37:31.980983
========
Revision ID: dd82ac7545c6
Revises: 
Create Date: 2024-12-16 23:38:11.018884
>>>>>>>> 9224ce6324b85ce667d0d49b9cb16220500c892d:migrations/versions/dd82ac7545c6_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/e3945611da63_initial_migration_after_cleanup.py
revision = 'e3945611da63'
========
revision = 'dd82ac7545c6'
>>>>>>>> 9224ce6324b85ce667d0d49b9cb16220500c892d:migrations/versions/dd82ac7545c6_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fileName', sa.String(length=40), nullable=False),
    sa.Column('imageUrl', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fileName')
    )
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('picture_url', sa.Text(), nullable=False),
    sa.Column('model_url', sa.Text(), nullable=False),
    sa.Column('uploaded_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=100), nullable=True),
    sa.Column('following', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('tag_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagDescription', sa.String(length=50), nullable=False),
    sa.Column('tagCount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tagDescription')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('card_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('uploadedDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('url')
    )
    op.create_table('comments_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('imageId', sa.Integer(), nullable=True),
    sa.Column('artId', sa.Integer(), nullable=True),
    sa.Column('threeId', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('uploadDate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['artId'], ['art_bank.id'], ),
    sa.ForeignKeyConstraint(['imageId'], ['card_bank.id'], ),
    sa.ForeignKeyConstraint(['threeId'], ['model.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('imageID', sa.Integer(), nullable=True),
    sa.Column('artId', sa.Integer(), nullable=True),
    sa.Column('threeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artId'], ['art_bank.id'], ),
    sa.ForeignKeyConstraint(['imageID'], ['card_bank.id'], ),
    sa.ForeignKeyConstraint(['threeId'], ['model.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments_bank')
    op.drop_table('card_bank')
    op.drop_table('user')
    op.drop_table('tag_list')
    op.drop_table('settings')
    op.drop_table('model')
    op.drop_table('art_bank')
    # ### end Alembic commands ###
